apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "strapi-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "strapi-app.fullname" . }}
    spec:
      containers:
      - name: {{ include "strapi-app.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 1337
        env:
        - name: APP_NAME
          value: "strapi-app"
        - name: DATABASE_CLIENT
          value: "mongo"
        - name: DATABASE_HOST
          value: "mongo-svc"
        - name: DATABASE_PORT
          value: "27017"
        - name: DATABASE_NAME
          value: "strapi"
        - name: DATABASE_USERNAME
          value: ""
        - name: DATABASE_PASSWORD
          value: ""
        - name: DATABASE_SSL
          value: "false"
        - name: DATABASE_AUTHENTICATION_DATABASE
          value: "strapi"
        - name: HOST
          value: "127.0.0.1"
