apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.db.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  serviceName: {{ .Values.db.name }}-svc
  replicas: {{ .Values.replicaCountdb }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Values.db.name }}
        image: {{ .Values.image.repositorydb }}
        ports:
        - containerPort: {{ .Values.service.portdb }}
          name: {{ .Values.db.name }}
        volumeMounts:
        - name: {{ .Values.db.name }}-ps
          mountPath: /data/db
        env:
          - name: MONGO_INITDB_DATABASE
            value: "strapi"
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.db.name }}-ps
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
