apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}-svc
  labels:
    app: {{ .Values.db.name }}
spec:
  ports:
  - port: {{ .Values.service.portdb }}
    name: {{ .Values.db.name }}
  clusterIP: None
  selector:
    app: {{ .Values.db.name }}

