apiVersion: v1
kind: Service
metadata:
  name: {{ include "strapi-app.name" . }}-svc
  labels:
    app: {{ include "strapi-app.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1337
      protocol: TCP
      name: https
  selector:
    app: {{ include "strapi-app.fullname" . }}