# Default values for strapi-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
replicaCountdb: 1

image:
  repository: matiri132/strapibuffer
  repositorydb: mongo
  tag: latest
  pullPolicy: IfNotPresent


nameOverride: "strapi"
fullnameOverride: "strapi-app"

service:
  port: 80
  portdb: 27017

db:
  name: mongo


ingress:
  name: strapi-ingress
  enabled: true
  hosts:
    - host: b.efn.unc.edu.ar
      paths: [/]


